name = mcl_cblocks
description = Adds colored variants of common blocks for Mineclonia.
depends = mcl_core, mcl_dyes, mcl_stairs
optional_depends = mcl_sounds, mcl_moreblocks
license = CC BY 3.0
media_license = CC BY 3.0
